DROP TABLE IF EXISTS TASK_TEMPLATE_COL;
CREATE TABLE TASK_TEMPLATE_COL
(
	TEMPLATE_COL_ID BIGINT AUTO_INCREMENT COMMENT '表ID，主键，供其他表做外键'
		PRIMARY KEY,
	TEMPLATE_ID BIGINT NULL COMMENT '任务模板定义表HPM_SETUP_TASK_TEMPLATE_DEFINE.TEMPLATE_ID',
	SERIAL_NUMBER DECIMAL NULL COMMENT '序号',
	COL_NAME VARCHAR(50) NULL COMMENT '列名',
	COL_DESC VARCHAR(100) NULL COMMENT '列描述',
	FORMAT_CODE VARCHAR(20) NULL COMMENT '格式HPM_SETUP_SYS_FORMAT',
	REQUIRED_FLAG VARCHAR(1) DEFAULT 'N' NULL COMMENT '是否必输'
)
COMMENT '任务模板行表';

DROP TABLE IF EXISTS TASK_TEMPLATE_DEFINE;
CREATE TABLE TASK_TEMPLATE_DEFINE
(
	TEMPLATE_ID BIGINT AUTO_INCREMENT COMMENT '表ID，主键，供其他表做外键'
		PRIMARY KEY,
	TEMPLATE_CODE VARCHAR(100) NOT NULL COMMENT '模板CODE',
	TEMPLATE_NAME VARCHAR(100) NULL COMMENT '模板名称',
	ENABLED_FLAG VARCHAR(1) DEFAULT 'Y' NULL COMMENT '启用标识',
	LOCK_FLAG VARCHAR(1) DEFAULT 'N' NULL COMMENT '锁定标识',
	TEMPLATE_TYPE VARCHAR(20) NULL COMMENT '模板类型',
	CONSTRAINT TEMPLATE_CODE
		UNIQUE (TEMPLATE_CODE)
)
COMMENT '任务模板表';







