server:
  port: 8079
  servlet:
    context-path: /

logging:
  level:
    root: debug

dubbo:
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  registry:
    id: dubbo-provider-registry
    address: zookeeper://localhost:2181