spring:
  datasource:
    ds1:
      password: 123456
      username: kmj
      jdbc-url: jdbc:postgresql://localhost:5432/mds1
      driver-class-name: org.postgresql.Driver
    ds2:
      password: 123456
      username: kmj
      jdbc-url: jdbc:postgresql://localhost:5432/mds2
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          # 避免报错，postgresql 驱动库 createClob 没实现
          use_jdbc_metadata_defaults: false

persist:
  type: jpa